### ISSUE TITLE
Add lintr

### ISSUE THREAD

**Issue by francisbarton** [nhs-r-community/NHSRpostcodetools#17]

**Comment by Lextuga007** [comment]
🙂 just checking what you mean from add lintr?

**Comment by francisbarton** [comment]
I wasn't sure either! Turns out I was thinking of `lintr::use_lintr` which creates a `.lintr` config file in the project root where you can set options about which linters you want the package to run, and any specific config options, for example you might want to set a max line length of 92 instead of the default 80 characters.

**Comment by Lextuga007** [comment]
Oh I see, yes of course because 80 characters can be restrictive (particularly if you ever have SQL code in a package I've found).
