### ISSUE TITLE
We don't need both batch_it() and batch_it_simple() in this package

### ISSUE THREAD

**Issue by francisbarton** [nhs-r-community/NHSRpostcodetools#20]
Pick 1 (the simpler one for the purposes of the postcode function), and work with it.
Code can almost certainly be improved while we're at it - it's a very elderly function now.

**Comment by Lextuga007** [comment]
Picking up this issue which you've already written 🚀 We should use the function from your {boundr} package if `batch_it()` is needed https://github.com/francisbarton/boundr/blob/c0084cc09780aa27edc94c407c63c9d37af9ac0d/R/bounds.R#L220. 

Would it be better just to depend upon {boundr}?

**Comment by francisbarton** [comment]
I think better to avoid the dependency if we can. It's a simple and solid enough function that I think just copy the code over, it doesn't matter if it diverges at all from the orig.
