### ISSUE TITLE
Fixing "no visible binding for global variable" note

### ISSUE THREAD

**Issue by Lextuga007** [nhs-r-community/NHSRpostcodetools#25]
https://community.rstudio.com/t/how-to-solve-no-visible-binding-for-global-variable-note/28887/3?u=shamindras

**Comment by francisbarton** [comment]
Is this from running `lintr`? I can't see any notes like this in CMD check (`devtools::check()`) on the main branch.

With lintr, unless you do `devtools::load_all()` first, `object_usage_linter()` will [complain about global variables](https://lintr.r-lib.org/articles/lintr.html) for things that are perfectly fine such as function names.

> Note that some linters (e.g. `object_usage_linter()`) require the package to be installed to function properly. `pkgload::load_all()` will also suffice. See `?executing_linters` for more details.

**Comment by Lextuga007** [comment]
It might have been! When I run it now I don't get any messages so closing 😄
