### ISSUE TITLE
Error in ui_info("The length of the target vector `x` is not an exact multiple of the\n    batch length(s) supplied

### ISSUE THREAD

**Issue by Lextuga007** [nhs-r-community/NHSRpostcodetools#6]
Error:

> Error in ui_info("The length of the target vector `x` is not an exact multiple of the\n    batch length(s) supplied. The remaining elements of `x` will be added as a\n    final batch.") :   could not find function "ui_info"

with code:

```
library(tidyverse)
library(PostcodesioR)

# Generate random example postcodes
postcodes <- purrr::map_chr(
  1:10,
  .f = ~PostcodesioR::random_postcode() |> 
    purrr::pluck(1) 
) |> 
  as_tibble()

NHSRpostcodetools::postcode_data_join(postcodes$value)

```

Also if the as_tibble() is removed and `NHSRpostcodetools::postcode_data_join(postcodes)`  however if the original function is run on the vectors, not tibble, `myrmidon::postcode_data_join(.data = postcodes2)` data is returned.

**Comment by francisbarton** [comment]
Hi Zoe
Thanks for pushing this on.
The `ui_info()` function comes from {usethis} and in my myrmidon package this was explicitly imported in the [package doc file](https://github.com/francisbarton/myrmidon/blob/81379748c2a46214aad8a17073236ab1a54576ef/R/myrmidon-package.R#L21). Hence why it isn't namespaced in the code (just saving space in some places).

If you replace it with `usethis::ui_info()` - or do a `usethis::use_package_doc()` and import it there in the same way as above - then the error should go away.

**Comment by Lextuga007** [comment]
I'll do that now, really appreciate the solution 😄
